### ISSUE TITLE
希望能加一个是否包含视频简介的选项

### ISSUE THREAD

**Issue by yi03** [Anillc/koishi-plugin-bilibili#1]
解析 B 站视频链接功能现在会带上简介，但是有些视频的简介非常长，有些刷屏，希望能加个选项可以不带简介。

**Comment by Anillc** [comment]
添加了限制简介长度的选项，更新后即可配置。

**Comment by TatleCat** [comment]
就是更改为
1: 不受限制
0: 关闭简介
其余数额自定义嘛 _(:з」∠)_

**Comment by Anillc** [comment]
> 就是更改为 1: 不受限制 0: 关闭简介 其余数额自定义嘛 _(:з」∠)_

`lengthLimit` 选项是简介长度，大于某个长度之后简介会被截断并在后面添加一个省略号

**Comment by TatleCat** [comment]
hh,我当然知道qwq
可以将我上面说的"就是"换成"可以"
就是可以的话,也希望将此列入下次的有必要更新
没有关闭简介. 显示:"简介:当..."
强迫症会有点麻_(:з」∠)_
麻烦到了的话,就无需回复我了(º﹃º )
