### ISSUE TITLE
新增用户请求失败

### ISSUE THREAD

**Issue by eric2788** [Anillc/koishi-plugin-bilibili#10]
所有正确uid都返回

```json
{
    "code": -352,
    "message": "-352",
    "ttl": 1
}
```

应该是有新的请求机制

**Comment by eric2788** [comment]
我看到有重复的了

**Comment by eric2788** [comment]
#5 这个问题还在

**Comment by eric2788** [comment]
我先重开issue
解决方式应该是这个: https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/user/info.md

**Comment by univeous** [comment]
请求时用自己的cookie能成功添加了。我提个pr(
