### ISSUE TITLE
催更(?    _(:з」∠)_

### ISSUE THREAD

**Issue by TatleCat** [Anillc/koishi-plugin-bilibili#3]
uhm... 这个插件还有在更新嘛
动态监听功能貌似不可用
已有调用权限,但是无反应
开启对应功能后,除插件设置中的指令外
指令与反馈文本不存在于列表中
        ——[安卓端koishi]   ∠( ᐛ 」∠)＿

**Comment by Anillc** [comment]
能否提供更详细的信息，我这边测试是可以使用的。开启功能后有没有重载插件呢

**Comment by TatleCat** [comment]
打扰了. 我试着把所有插件都使用最新
重载插件后依旧没有用,重启koishi解决了

那,还有另外一个小改动就是
希望同步哔站动态后面可以加个换行

比如
[114514]发布了动态:
哼哼哼啊啊啊啊啊啊啊啊
而不是
[114514]发布了动态:哼哼哼啊啊啊
啊啊啊啊啊

可以累积到下一次的有必要更新qwq

**Comment by Anillc** [comment]
好的
