### ISSUE TITLE
在uid正确的情况下dynamic.add失败

### ISSUE THREAD

**Issue by KIRA2ZERO** [Anillc/koishi-plugin-bilibili#5]
![W~$PLR9OADA) NAC7JWDCOH](https://github.com/Anillc/koishi-plugin-bilibili/assets/120578649/e3d28598-6642-40d0-9feb-9b7b968c2b80)
![image](https://github.com/Anillc/koishi-plugin-bilibili/assets/120578649/e21fe2f1-7f07-4a33-b0d0-4223b2a961ba)
bot挂在新加坡阿里云上，discord平台

**Comment by Anillc** [comment]
已修复，请更新到最新版本重新尝试
